// GET/READ MAIN DATA
export const GET_DATA_FISH_REQUEST = 'GET_DATA_FISH_REQUEST'
export const GET_DATA_FISH_SUCCESS = 'GET_DATA_FISH_SUCCESS'
export const GET_DATA_FISH_FAIL = 'GET_DATA_FISH_FAIL'

// GET/READ PROVINCE & CITY DATA
export const GET_DATA_AREA_REQUEST = 'GET_DATA_AREA_REQUEST'
export const GET_DATA_AREA_SUCCESS = 'GET_DATA_AREA_SUCCESS'
export const GET_DATA_AREA_FAIL = 'GET_DATA_AREA_FAIL'

export const GET_DATA_SIZE_REQUEST = 'GET_DATA_SIZE_REQUEST'
export const GET_DATA_SIZE_SUCCESS = 'GET_DATA_SIZE_SUCCESS'
export const GET_DATA_SIZE_FAIL = 'GET_DATA_SIZE_FAIL'

// CREATE NEW DATA
export const CREATE_DATA_REQUEST = 'CREATE_DATA_REQUEST'
export const CREATE_DATA_SUCCESS = 'CREATE_DATA_SUCCESS'
export const CREATE_DATA_FAIL = 'CREATE_DATA_FAIL'

// EDIT/UPDATE DATA
export const UPDATE_DATA_REQUEST =  'UPDATE_DATA_REQUEST'
export const UPDATE_DATA_SUCCESS =  'UPDATE_DATA_SUCCESS'
export const UPDATE_DATA_FAIL =  'UPDATE_DATA_FAIL'

// DELETE DATA
export const DELETE_DATA_REQUEST = 'DELETE_DATA_REQUEST'
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS'
export const DELETE_DATA_FAIL = 'DELETE_DATA_FAIL'

// RESET STATE
export const RESET_REQUEST_ERROR = 'RESET_REQUEST_ERROR'
